---
- name: install apache
  hosts: all
  gather_facts: yes
  become: true
  vars:
    software1:
      - apache2
    software2:
      - httpd 

  tasks:

  - name: install apache
    apt:
      name: "{{ software1 }}"
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd in centos
    yum:
      name: "{{ software2 }}"
      state: latest
    when: ansible_distribution == "Amazon"
